### ISSUE TITLE
Dropdown menu does not fit in window, requires horizontal scrolling

### ISSUE THREAD

**Issue by JeffryErickson** [andryou/scriptsafe#17]
When I click the ScriptSafe icon, the dropdown menu does not fit within the dropdown window. I have to use the slider at the bottom of the window to see the whole thing. This does not happen with other add-ins. Very occasionally (but not usually) if I change the zoom level of the browser tab before I click the ScriptSafe icon, this problem goes away. I have attached a screenshot.

I am on Chrome (V 51.0.2704.79 m) on Windows 7, ScriptSafe V 1.0.7.4.

This seems similar to issue #7 but different enough I thought I wouldn't hijack that issue.
![2016-06-02 andryou_scriptsafe screen shot](https://cloud.githubusercontent.com/assets/8669365/15758041/409a8624-28ce-11e6-9f16-afbcd650c309.jpg)

**Comment by andryou** [comment]
Yikes, will fix and push out an update asap. Thanks!

**Comment by andryou** [comment]
I've just pushed v1.0.7.5. Please let me know if this issue is fixed after updating :)

**Comment by JeffryErickson** [comment]
Thanks for the quick attention, but unfortunately it is still showing the same symptoms.

**Comment by andryou** [comment]
Do you remember which version it was displaying properly in?

**Comment by JeffryErickson** [comment]
I have tried restarting Chrome. It has been a problem for quite a few days, but not weeks but I did not think to check the version when it first started happening.

**Comment by andryou** [comment]
Thanks, I'm working on making some minor CSS tweaks and will push an update in a couple hours or tomorrow.

Side-note: something strange I noticed is that the footer in the panel in your screenshot is that of v1.0.7.3 (with the "Quick Start | Overview" links that I changed to "Documentation" in v1.0.7.4)

**Comment by andryou** [comment]
New update v1.0.7.7 pushed out. Please try and close this issue if it's working for you :)

**Comment by JeffryErickson** [comment]
Sorry, but it still is happening!

**Comment by andryou** [comment]
Please try v1.0.7.8 and close this issue if resolved, thanks!

**Comment by andryou** [comment]
(sorry for the delay in getting v1.0.7.8 to you; it's been "Pending Review" in the Chrome Web Store since I pushed it out 8:45pm eastern yesterday)

**Comment by andryou** [comment]
I've been refreshing the Developer Dashboard all day to check on the status and I'm happy to announce v1.0.7.8 has been published on the Chrome Web Store within the past half hour.

**Comment by JeffryErickson** [comment]
It is better - I can see more of the dropdown menu but still not all. I still have to scroll to the right to get to the X to close the window (although I usually just click outside the menu)..

**Comment by andryou** [comment]
Good to hear there's some improvement, can you please post a screenshot so I can gauge the values? Thanks!

**Comment by JeffryErickson** [comment]
Here is a new screenshot.
![scriptsafe dropdown menu 2016-06-07 12_31_28](https://cloud.githubusercontent.com/assets/8669365/15868215/70004dfe-2cac-11e6-84a7-99ccec813d11.jpg)

**Comment by andryou** [comment]
Thanks, do you have your system font set to 125% or 150%? And if so, which value?

![2016-06-07 17_43_56](https://cloud.githubusercontent.com/assets/4351175/15875745/85040f76-2cd7-11e6-8946-ddec3fb16942.png)

Just wondering so I can set my machine to the same to debug this. Thanks!

**Comment by JeffryErickson** [comment]
Windows is set at medium, 125%. I have Chrome set zoomed as well, but it looks like that might vary by tab. A new default tab comes in at 125%

**Comment by andryou** [comment]
@JeffryErickson has this improved for you in any way with the latest updates?

**Comment by JeffryErickson** [comment]
No, sorry! (I am on .7.10 now)

**Comment by MaWo123** [comment]
I have the same problem...is there any solution by now?

**Comment by MaWo123** [comment]
![Uploading scriptsave.jpg…]()

**Comment by JeffryErickson** [comment]
I still have the problem, too.

**Comment by andryou** [comment]
Which ScriptSafe version are you both on? The panel has been updated to a one-column layout as of v1.0.9.0.

I just tested it with my system font set at 125%:

![2017-01-19 10_33_14](https://cloud.githubusercontent.com/assets/4351175/22112974/d645ac98-de32-11e6-9f48-ed1d73eb33c8.png)
(please disregard the version in the screenshot)

Are there any other settings that you've modified?

**Comment by JeffryErickson** [comment]
I am on version 1.0.8.5. I tried updating but Chrome is not pulling in v1.09. My system font is also at 125%. I believe my ScriptSafe options are all at their defaults.

**Comment by andryou** [comment]
@JeffryErickson please let me know when v1.0.9.0 is propagated to your machine :) I'm hoping that the one-column layout resolves the horizontal spanning issue!

**Comment by JeffryErickson** [comment]
I uninstalled and re-installed and am now on v1.0.9.0 - but the problem remains unfortunately :(
![scripsafe page fit](https://cloud.githubusercontent.com/assets/8669365/22121868/3c11a0aa-de4b-11e6-94bb-727dce07d436.jpg)

**Comment by andryou** [comment]
Thanks; I think I have an idea of how to resolve this, I'll look into it today and I'll keep you updated!

**Comment by MaWo123** [comment]
I have a chrome skin, but i also tried to turn it off. no change. systemfont is 100%.

![scriptsave](https://cloud.githubusercontent.com/assets/25226219/22122642/05320b68-de89-11e6-8461-37660ae5bc8a.png)

**Comment by andryou** [comment]
I've worked on converting the font sizes and widths to be fluid and created a test build for you to try on your machines.

Could you both do me a favour and test it out? https://dl.dropboxusercontent.com/u/784305/scriptsafe_test.zip

Thank you! Instructions on how to install it:

2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #1 and click on OK

Then please open a site and open the ScriptSafe panel and let me know if there is any improvement.

Once done testing, you can simply remove the test ScriptSafe build and re-enable the Chrome Web Store version.

**Comment by MaWo123** [comment]
Yes! That is working perfectly. Everything fits in the dropdown window. thank you :)
The only thing for me now is that i somehow dont have the 3 buttons that you have in your screenshots (Allow all blocked for Session, Revoke page temp permissions and revoke all temp)

**Comment by andryou** [comment]
That's great to hear! :)

Allow all blocked for Session = appears when items have been blocked on a tab. Try going to www.cnn.com and click on "Temporary" to allow external resources to load, then open the panel again and this should appear.

Revoke page temp permissions and revoke all temp = if you temporarily allow something in a tab, these two buttons will appear. If you're on a tab with nothing temporarily allowed, but you have temporarily allowed something in a different tab, only "Revoke All Temp" will appear.

**Comment by MaWo123** [comment]
ahhh nice, never noticed that before, because i would've had to scoll down^^

looking forward to next version....and thanks again for the really fast support

**Comment by JeffryErickson** [comment]
Your test build worked perfectly - great!
Thanks for being responsive!

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by JeffryErickson** [comment]
I loaded the Beta and everything seems to work perfectly so far. I can see the entire drop-down window. Great!

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue. Thanks again for your report and testing!

**Comment by JeffryErickson** [comment]
Sorry to bear bad news. v1.0.9.1 BETA worked, v1.0.9.1 non-beta does not. Screen shots attached. I restarted Chrome between each version. Advice?
![scriptsafe v1 0 9 1 beta](https://cloud.githubusercontent.com/assets/8669365/22388438/2242c5c6-e4a6-11e6-9504-3a7dd698861e.jpg)
![scriptsafe v1 0 9 1](https://cloud.githubusercontent.com/assets/8669365/22388437/2241d9fe-e4a6-11e6-91b7-91ac312e0eab.jpg)

**Comment by andryou** [comment]
@JeffryErickson very interesting! Thank you for retesting. I will re-open this issue.

I just compared the changes between v1.0.9.1 beta and the stable version: https://github.com/andryou/scriptsafe/compare/v1.0.9.1_beta...master

The only change I made was removing 5 pixels from the top of the panel, bringing the tab domain box closer to the ScriptSafe heading.

Could you try downloading v1.0.9.1 from https://github.com/andryou/scriptsafe/releases/tag/v1.0.9.1 and loading it into Chrome following the same instructions I provided earlier in this ticket, and let me know if the panel still has the issue? (https://github.com/andryou/scriptsafe/issues/17#issuecomment-273930528)

If it displays properly, then it sounds like there is a weird bug in Chrome with local extensions vs extensions added from the Web Store.

**Comment by JeffryErickson** [comment]
It looks like "weird bug" is right. I loaded the extension from Github and the problem goes away. In fact I can toggle on and off the local extension vs the Web Store extension and the problem comes and goes with it!

**Comment by MaWo123** [comment]
anything new ? still have the same bug if i use the normal release...currently using the beta but my browser tell me everytime that i shouldn't use it in developer mode.

**Comment by MaWo123** [comment]
still the same bug. and the beta version somehow uninstalled itself.

**Comment by MaWo123** [comment]
anything new?

**Comment by w8n41** [comment]
This is exactly the same thing I am experiencing. The menu continues to be broken.
