### ISSUE TITLE
Permission buttons don't work on non-primary monitor

### ISSUE THREAD

**Issue by usbruce** [andryou/scriptsafe#253]
Happens with Chrome Beta 62 and Chrome Canary 63 and prior versions on Windows 7 and Windows 10.

When Chrome is displayed on a second monitor and I click the ScriptSafe button to show the permissions dialog, clicking on the permissions buttons (Allow, Trust, Temporary) doesn't work. Instead, I need to move the browser back to the main monitor to set the site permissions.

This has been happening for some time and the workaround isn't a big deal, but I thought I should drop you a note so you can add this to your issues queue.

Thank you!

**Comment by DoNuT1985** [comment]
Having the same issue on Chrome 61.0.3163.100

**Comment by DoNuT1985** [comment]
Not an extension issues, same problem with AdBlock Plus and Feedly Notifier that also draw such overlays, so probably a Problem with Chrome itself.

**Comment by andryou** [comment]
Just catching up on issues, it seems this has been resolved on Chrome's end: can you confirm?

Thank you! I appreciate your proactivity.

**Comment by DoNuT1985** [comment]
Works now on multi-monitor setups as well. Can't tell which exact Chrome version fixed it as there's been at least a two updates but can consider this resolved, IMHO.

**Comment by DoNuT1985** [comment]
Sorry, I haven't recognized as this mainly affects my work setup where I tend to use the same pages over and over again, but still an issue with Chrome 62. Interestingly the 'clear' label for the domain is the only one that's working, by the way...

![image](https://user-images.githubusercontent.com/9864643/33305809-f238dc3a-d40f-11e7-997e-bd604850b8a8.png)

**Comment by usbruce** [comment]
No issue...I was just passing on the info.  I also discovered the work-around as noted in your references on PrivacyBadger in that the relative coordinates within the Chrome window are off when Chrome is on a non-primary monitor.  I haven't tried different scenarios but for my primary workstation with 3 screens arranged across as FHD | 4K | FHD with screens aligned to their top edges, when Chrome is on the left monitor I need to click about 1 full button height above and about 1/2 button width to the left of where I want the click to register.  Mousing around will show where to click when the hover event triggers the underline to show on the button text.

I'm guessing this can all vary on Win10 scaling, desktop alignment positions, and possibly depend on where the task bar is docked. It will take a bit of experimentation to ensure all possibly combinations work in Chrome.

But, I totally agree this is a Chrome issue.

**Comment by jfhorn** [comment]
SOLUTION / better workaround: Per the Chromium forums, disable this flag in the browser/Chrome:
[chrome://flags/#enable-use-zoom-for-dsf
](chrome://flags/#enable-use-zoom-for-dsf)

This is a browser issue and in theory, the browser could auto-disable this feature if it detected multiple monitors running at different DPIs (or is it resolutions?).  This did not break browser functionality for me.

**Comment by fposch** [comment]
Confirming that disabling _Use Blink's zoom for device scale factor._ fixes the issue, no drawbacks on a WSXGA+| 4K | WSXGA+ setup.
