### ISSUE TITLE
UI doesn't extend fully

### ISSUE THREAD

**Issue by aantonop** [andryou/scriptsafe#4]
Happens at least 50% of the time and makes it very difficult to use ScriptSafe. 

Pressing the script safe icon is supposed to lower the UI to allow selection of permissions. Instead of lowering all the way, it lowers only about 25% or less (about the height of two of the UI buttons). This makes it impossible to select, say "Trust" or "Temp" on any of the listed resources because they are not visible. 

Repeatedly pressing the toolbar icon eventually drops the entire UI low enough to use it. 

Latest version v1.0.6.19

**Comment by andryou** [comment]
Does this happen on specific sites, or is it global?
And what operating system and version are you using?

If you right-click on the UI, click on Inspect, and click on the "Console" tab, can you copy/paste what you see (if any entries?)

**Comment by andryou** [comment]
Also did you try restarting Chrome? #7 sounds very similar to this and it may have been resolved with a browser restart (still need to be confirmed though)

**Comment by aantonop** [comment]
Chrome restart doesn't fix. This has been a persistent, intermittent, bug across at least 3 versions of ScriptSafe and several versions of Chrome, a constant annoyance for more than a year. Chrome (latest and several before that), MacOS Yosemite and also the previous version. 

Console on inspect of UI shows:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/. (popup.js)

The bug does not occur on any specific site. It occurs intermittently (frequently) on any site. Happens on both whitelisted and non-whitelisted (first visit) sites. It may occur for a while, then stop occurring. After several left-clicks I can usually get the full UI. 

Workaround: Keep left-clicking to cancel and re-engage the UI until it displays the full UI. May take 10+ attempts to get it to work.

**Comment by andryou** [comment]
@aantonop thanks for the info. Definitely sounds like a nasty bug and I apologize for not addressing it earlier. Right now I'm working on revamping the domain matching logic which touches almost all aspects of ScriptSafe, and I'll try to see if I can address this bug by optimizing the code (I'm a Windows user and cannot reproduce this, but I will try my best to simplify the code).

**Comment by andryou** [comment]
Just pushed the new version, v1.0.7.0, it should auto-update for you within 12 hours.

ScriptSafe should have higher performance overall, and hopefully it resolves this issue for you. If not, let me know and I'll continue to look into this!

**Comment by aantonop** [comment]
Bug still exists after upgrade to v1.0.7.0. First time I click on icon,
after restarting chrome, on a reddit (whitelisted page), the UI descended
only to the height of the "Allow all blocked in session" blue button. The
rest of the UI was hidden. As I'm typing this in gmail, the UI only descend
to show one of the entries on the left (the last domain in the list), the
rest of the UI is hidden. Exactly the same as before. Sorry, this is
probably a very obscure bug...

I'll attach a screen shot...


On Mon, May 30, 2016 at 12:47 PM, Andrew <notifications@github.com> wrote:

> Just pushed the new version, v1.0.7.0, it should auto-update for you
> within 12 hours.
>
> ScriptSafe should have higher performance overall, and hopefully it
> resolves this issue for you. If not, let me know and I'll continue to look
> into this!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andryou/scriptsafe/issues/4#issuecomment-222533604>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABII2yUEMBWau0tJUfprqWdKNrimx9rEks5qGyLIgaJpZM4Io7Lo>
> .
>



-- 
Andreas M. Antonopoulos
andreas@antonopoulos.com
Tel: +1 347 744 9404

**Comment by aantonop** [comment]
![screen shot 2016-05-30 at 6 09 28 pm](https://cloud.githubusercontent.com/assets/1181915/15659527/d2f86386-2691-11e6-98ba-522544eb55bb.png)

**Comment by aantonop** [comment]
This is in gmail.com, same thing:
![screen shot 2016-05-30 at 6 06 36 pm](https://cloud.githubusercontent.com/assets/1181915/15659535/fd6f5548-2691-11e6-88e0-c440c62bf220.png)

**Comment by aantonop** [comment]
One thing I notice is that it always drops the SAME height of UI, regardless of contents. Some time that includes a button, sometimes a domain, sometimes 1 1/2 button. Seems to be uncorrelated to the content of the UI panel and always the same height (visually, in inches) when it stops dropping further.

**Comment by andryou** [comment]
Thank you very much for the detailed examples. I'm going to focus on this issue because I can imagine it is very annoying and almost makes the panel useless.

**Comment by ROpdebee** [comment]
Been experiencing this as well for a long while now. Same symptoms as @aantonop, also on Mac OS X (El Capitan) through multiple versions of Chrome. Some of my findings:
- It can happen even if the panel opened successfully on the same page before (without reloading).
- Nothing shows up in the console for me, so whatever synchronous XHR @aantonop saw must've been an issue with the page itself.
- Might be just me, but this doesn't seem to be limited to just ScriptSafe... Whenever ScriptSafe's panel acts up, Tampermonkey's panel does too. When Tampermonkey is the first to start bugging out, ScriptSafe does as well.

I can try to debug some more if you can guide me in the right direction.

**Comment by ROpdebee** [comment]
Some more insights: From what I've seen, it seems to correctly render the whole popup but in a flash it gets resized to what seems to be the default size of the popup (judging from the HTML). The contents of the popup are inserted correctly but they seem to be hidden by the resizing. I've also found this very similar issue: https://productforums.google.com/forum/#!topic/chrome/4ofdh8EYL6Y

I've also noticed that forcing a re-render of the hidden content (e.g. by prepending some new element in the popup or by changing some CSS of the hidden elements) causes the popup to be shown completely.

So there's two possible fixes I can think of without actually knowing the root of the problem:
1. Right now, the popup is filled and it has to grow to display all the content, but it seems that this growing is messing up. So, one option would be to make sure the popup is by default big enough to store all the data and that it only has to shrink. That way, if the resizing of the popup acts up, users would still be able to use the panel even if it failed to resize. People may still complain about the panel being too big sometimes, but it's less annoying than no panel at all.

2. Another option would be to manually force a re-render every time the popup is shown. That way you'd ensure the panel gets drawn decently.

The best fix would of course still be actually finding what's causing this and fixing it, but seeing as apparently not only ScriptSafe is affected and you can't reproduce the bug, that might be somewhat difficult.

**Comment by andryou** [comment]
I've synced a potential simple fix to Github, can you please try downloading a ZIP of this repo and adding it as an unpacked extension to Chrome (no need to enable syncing while testing)? https://github.com/andryou/scriptsafe

Code change (a single line): https://github.com/andryou/scriptsafe/commit/05ad1e3e73743bd2165b232f97a8a85751779076

**Comment by ROpdebee** [comment]
I've just tested both, I can still reproduce the bug with the first attempt to fix. However, when initializing the panel is deferred (fix B), I have not yet encountered the issue. I've tested it on multiple sites, by now I probably clicked the button over 200 times and it always worked.

**Comment by andryou** [comment]
That's great news! Due to the significance of this "bug" (from my reading last night it is Chrome-related and seems to be affecting other Chrome extensions as well), I will be pushing an update later today or if @aantonop is able to test Fix B as well and confirm it consistently solves the issue.

**Comment by andryou** [comment]
Just pushed v1.0.7.2 which includes the fix in Fix B above. Code commit here: https://github.com/andryou/scriptsafe/commit/9566540a0a970ddfb230215a0aacc7cb415828cb

Please let me know if it resolves this issue. Thanks!

**Comment by ROpdebee** [comment]
A bit off-topic but regarding the panel generation code you refactored in the latest commit: Have you ever considered using a templating engine for rendering the panel HTML? That'd simplify the code and make it easier for you to change it later on. It shouldn't have too much of a performance impact provided you use some precompiled template, IIRC Handlebars.js has such a feature.

**Comment by ROpdebee** [comment]
Bad news, just found out it still happens but it seems to occur far less frequently. When I reopened the panel it solved itself instantly, which wasn't always the case before 1.0.7.2. So it's still there but it's much less of an annoyance than before, it seems. That's my experience with it anyway.

**Comment by andryou** [comment]
Thanks for testing, I think I'll set the value to 100 milliseconds instead of 0 which will hopefully make a difference.

**Comment by fr3aker** [comment]
I'm experiencing the same problem on all websites I'm visiting. The menu looks exactly like the screenshot in #7 with absolutely no UI buttons at all, only the info links and X to close.

I see this error in the console:

    Error in event handler for (unknown): TypeError: Cannot read property 'mode' of undefined
    at chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/popup.js:78:21

v1.0.7.6

**Comment by andryou** [comment]
@fr3aker thanks for the debugging and reporting. Very strange. Is "**.[" the entirety of the entry?

@ROpdebee, I've pushed out update v1.0.7.7 with an increased value of 25 (from 0ms). Please let me know if it's opening more consistent now.

**Comment by fr3aker** [comment]
Yes, the entry only consisted of those four characters.

**Comment by ROpdebee** [comment]
I've installed the new version and it seems to make it worse than before... I've gotten more of these occurrences in the last half hour than in the past few days combined. Very weird.

The last version with 0ms seemed to prevent the glitches most of the time and they were rare enough not to be annoying, IMO.

**Comment by andryou** [comment]
@ROpdebee thanks, will revert back to 0ms in the next update!

**Comment by andryou** [comment]
Reverted back to 0ms in v1.0.7.8. Going to close this issue based on the sense I'm getting that this issue has (mostly) been resolved as best as possible. Anyone is free to create another issue.

**Comment by andryou** [comment]
@ROpdebee could you test out this test build and let me know if the UI extends properly and consistently? https://dl.dropboxusercontent.com/u/784305/ScriptSafe_E.zip

You can comment in #56 with how this test build works for you. Thanks!
